Disable release-too-old check

diff --git a/.github/workflows/deploy_agent.yml b/.github/workflows/deploy_agent.yml
--- a/.github/workflows/deploy_agent.yml
+++ b/.github/workflows/deploy_agent.yml
@@ -109,12 +109,12 @@ jobs:
             echo "::error::Release publish date is empty. Use manual overrides to continue."
             exit 1
           fi
-          LAST_WEEK=$(date --date "-7days" -u +"%s")
-          PUBLISH_DATE=$(date --date "$PUBLISHED_AT" -u +"%s")
-          if [ $LAST_WEEK -ge $PUBLISH_DATE ]; then
-            echo "::error::$RELEASE_VERSION was published more than a week ago. Use manual overrides to continue."
-            exit 1
-          fi
+          #LAST_WEEK=$(date --date "-7days" -u +"%s")
+          #PUBLISH_DATE=$(date --date "$PUBLISHED_AT" -u +"%s")
+          #if [ $LAST_WEEK -ge $PUBLISH_DATE ]; then
+          #  echo "::error::$RELEASE_VERSION was published more than a week ago. Use manual overrides to continue."
+          #  exit 1
+          #fi
 
           echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
 
